/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUpcomingRouteImport } from './routes/_app/upcoming'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AppPeopleIdRouteImport } from './routes/_app/people.$id'
import { Route as AppTitlesIdRouteImport } from './routes/_app/titles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUpcomingRoute = AppUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTitlesIdRoute = AppTitlesIdRouteImport.update({
  id: '/titles/$id',
  path: '/titles/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/upcoming': typeof AppUpcomingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/titles/$id': typeof AppTitlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/upcoming': typeof AppUpcomingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/titles/$id': typeof AppTitlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upcoming': typeof AppUpcomingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/people/$id': typeof AppPeopleIdRoute
  '/_app/titles/$id': typeof AppTitlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/dashboard'
    | '/explore'
    | '/history'
    | '/library'
    | '/onboarding'
    | '/settings'
    | '/upcoming'
    | '/login'
    | '/register'
    | '/people/$id'
    | '/titles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/dashboard'
    | '/explore'
    | '/history'
    | '/library'
    | '/onboarding'
    | '/settings'
    | '/upcoming'
    | '/login'
    | '/register'
    | '/people/$id'
    | '/titles/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/setup'
    | '/_app/dashboard'
    | '/_app/explore'
    | '/_app/history'
    | '/_app/library'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/_app/upcoming'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/people/$id'
    | '/_app/titles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upcoming': {
      id: '/_app/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof AppUpcomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/titles/$id': {
      id: '/_app/titles/$id'
      path: '/titles/$id'
      fullPath: '/titles/$id'
      preLoaderRoute: typeof AppTitlesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUpcomingRoute: typeof AppUpcomingRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppTitlesIdRoute: typeof AppTitlesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExploreRoute: AppExploreRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUpcomingRoute: AppUpcomingRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppTitlesIdRoute: AppTitlesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
